/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaexcercises;

import java.util.Arrays;
import java.util.HashSet;
import java.util.stream.IntStream;

/**
 *
 * @author JC
 */
public class FindTheDifference {
    
    /*
    Given two strings s and t which consist of only lowercase letters.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Find the letter that was added in t.
    
    **Example:
    Input:
        s = "abcd"
        t = "abcde"
    Output:
        e
    Explanation:
        'e' is the letter that was added.
    */
    
    public static void main(String[] args) {
        // pass two strings
        char res = findTheDifference("ymbgaraibkfmvocpizdydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmoswrcxnargtlswqemafandgkmydtimuzvjwxvlfwlhvkrgcsithaqlcvrihrwqkpjdhgfgreqoxzfvhjzojhghfwbvpfzectwwhexthbsndovxejsntmjihchaotbgcysfdaojkjldprwyrnischrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuinkyygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczcovrmwqxxbnhfzcjjcpgzjjfateajnnvlbwhyppdleahgaypxidkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjszolgwqvfiozofncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrrymrfdxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpqsspyssrmdhuelkkvyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxkvwkrwdcxjfzikdyswsuxegmhtnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfovaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrcwjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtelhwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdjkfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgddqwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor", "qhxepbshlrhoecdaodgpousbzfcqjxulatciapuftffahhlmxbufgjuxstfjvljybfxnenlacmjqoymvamphpxnolwijwcecgwbcjhgdybfffwoygikvoecdggplfohemfypxfsvdrseyhmvkoovxhdvoavsqqbrsqrkqhbtmgwaurgisloqjixfwfvwtszcxwktkwesaxsmhsvlitegrlzkvfqoiiwxbzskzoewbkxtphapavbyvhzvgrrfriddnsrftfowhdanvhjvurhljmpxvpddxmzfgwwpkjrfgqptrmumoemhfpojnxzwlrxkcafvbhlwrapubhveattfifsmiounhqusvhywnxhwrgamgnesxmzliyzisqrwvkiyderyotxhwspqrrkeczjysfujvovsfcfouykcqyjoobfdgnlswfzjmyucaxuaslzwfnetekymrwbvponiaojdqnbmboldvvitamntwnyaeppjaohwkrisrlrgwcjqqgxeqerjrbapfzurcwxhcwzugcgnirkkrxdthtbmdqgvqxilllrsbwjhwqszrjtzyetwubdrlyakzxcveufvhqugyawvkivwonvmrgnchkzdysngqdibhkyboyftxcvvjoggecjsajbuqkjjxfvynrjsnvtfvgpgveycxidhhfauvjovmnbqgoxsafknluyimkczykwdgvqwlvvgdmufxdypwnajkncoynqticfetcdafvtqszuwfmrdggifokwmkgzuxnhncmnsstffqpqbplypapctctfhqpihavligbrutxmmygiyaklqtakdidvnvrjfteazeqmbgklrgrorudayokxptswwkcircwuhcavhdparjfkjypkyxhbgwxbkvpvrtzjaetahmxevmkhdfyidhrdeejapfbafwmdqjqszwnwzgclitdhlnkaiyldwkwwzvhyorgbysyjbxsspnjdewjxbhpsvj");
        System.out.println("Find the Difference Result: " + res);
    }
    // SIN RESOLVER
    public static char findTheDifference(String s, String t) {
        char c;
        int mayor;
        //System.out.println("" + s.length());
        //System.out.println("" + t.length());
        if (s.length() > t.length())
            c = getChar(s.length(), s, t);
        else
            c = getChar(t.length(), t, s);
        
        HashSet<Character> h1 = new HashSet<Character>(), h2 = new HashSet<Character>();
        for(int i = 0; i < s.length(); i++)                                            
        {
          h1.add(s.charAt(i));
        }
        for(int i = 0; i < t.length(); i++)
        {
          h2.add(t.charAt(i));
        }
        h1.retainAll(h2);
        String al = s + t;
        IntStream add = s.chars().distinct();
        String op = add.toString();
        System.out.println("" + op);
        Character[] res = h1.toArray(new Character[0]);
        for (Character re : res) {
            //System.out.println("" + re);
        }
        return c;
    }
    /*
     @param int
    */
    public static char getChar(int m, String mayor, String menor) {
        char c = 'a';
        char[] charA = mayor.toCharArray();
        char[] charB = menor.toCharArray();
        Arrays.sort(charA);
        Arrays.sort(charB);
        mayor = new String(charA);
        menor = new String(charB);
        boolean flag = false;
        int cont = mayor.length() - 1;
        
        for (int i = 0; i < m; i++) {
            for (int j = 0; j < m; j++) {
                try {
                    
                    if (menor.charAt(i) == mayor.charAt(j)) {
                        flag = true;
                    }
                    else {
                        c = mayor.charAt(j);
                    }
                    
                } catch (StringIndexOutOfBoundsException e) {
                    //System.out.println("" + e.getMessage());
                    if (!flag && cont == j) {
                        c = mayor.charAt(j);
                    }
                }
            }
            
            
        }
        return c;
    }
    
}
